# Generated by Django 5.1.4 on 2026-04-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_privacy_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='politique de confidentialité acceptée le'),
        ),
        migrations.AddField(
            model_name='user',
            name='accepted_terms_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='CGU acceptées le'),
        ),
    ]
