# Generated by Django 5.1.4 on 2026-05-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_accepted_privacy_at_user_accepted_terms_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('fr', 'Français'), ('nl', 'Nederlands'), ('en', 'English')], default='fr', max_length=10, verbose_name='langue préférée'),
        ),
    ]
