# Generated by Django 5.1.4 on 2026-10-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='anonymised_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='anonymisé le'),
        ),
    ]
