# Generated by Django 5.1.4 on 2026-04-25 16:59

import apps.companies.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_seed_communes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='dénomination')),
                ('vat_number', models.CharField(help_text='Format : BE0XXXXXXXXX.', max_length=15, validators=[apps.companies.models.validate_belgian_vat], verbose_name='numéro TVA')),
                ('activity', models.CharField(blank=True, max_length=200, verbose_name='activité')),
                ('street', models.CharField(max_length=200, verbose_name='rue')),
                ('number', models.CharField(max_length=20, verbose_name='numéro')),
                ('box', models.CharField(blank=True, max_length=20, verbose_name='boîte')),
                ('postal_code', models.CharField(max_length=10, verbose_name='code postal')),
                ('country', models.CharField(default='BE', max_length=2, verbose_name='pays')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='core.commune', verbose_name='commune')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'entreprise',
                'verbose_name_plural': 'entreprises',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'vat_number'), name='unique_vat_per_owner')],
            },
        ),
    ]
