# Generated by Django 5.1.4 on 2026-04-25 15:02

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_number', models.CharField(blank=True, max_length=15, verbose_name='numéro national')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='citizen_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil citoyen',
                'verbose_name_plural': 'profils citoyens',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200, verbose_name='rue')),
                ('number', models.CharField(max_length=20, verbose_name='numéro')),
                ('box', models.CharField(blank=True, max_length=20, verbose_name='boîte')),
                ('postal_code', models.CharField(max_length=10, verbose_name='code postal')),
                ('country', models.CharField(default='BE', max_length=2, verbose_name='pays')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='point géocodé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='core.commune', verbose_name='commune')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='citizens.citizenprofile')),
            ],
            options={
                'verbose_name': 'adresse',
                'verbose_name_plural': 'adresses',
            },
        ),
    ]
