# Generated by Django 5.1.4 on 2026-04-25 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0001_initial'),
        ('core', '0002_seed_communes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200, verbose_name='rue')),
                ('number', models.CharField(max_length=20, verbose_name='numéro')),
                ('box', models.CharField(blank=True, max_length=20, verbose_name='boîte')),
                ('postal_code', models.CharField(max_length=10, verbose_name='code postal')),
                ('country', models.CharField(default='BE', max_length=2, verbose_name='pays')),
                ('reason', models.TextField(blank=True, verbose_name='motif')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Refusée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='statut')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True, verbose_name='notes')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commune', verbose_name='commune')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_change_requests', to='citizens.citizenprofile')),
            ],
            options={
                'verbose_name': "demande de changement d'adresse",
                'verbose_name_plural': "demandes de changement d'adresse",
                'ordering': ['-submitted_at'],
            },
        ),
    ]
