# Generated by Django 5.1.4 on 2026-04-25 15:47

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_seed_communes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GISSourceVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('source_filename', models.CharField(max_length=255, verbose_name='fichier source')),
                ('srid', models.IntegerField(verbose_name='SRID')),
                ('polygon_count', models.IntegerField(default=0, verbose_name='nombre de polygones')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'version GIS',
                'verbose_name_plural': 'versions GIS',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='GISPolygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=31370)),
                ('zonecode', models.CharField(db_index=True, max_length=100, verbose_name='zonecode')),
                ('niscode', models.CharField(db_index=True, max_length=10, verbose_name='niscode')),
                ('type', models.CharField(blank=True, max_length=50, verbose_name='type')),
                ('layer', models.CharField(blank=True, max_length=100, verbose_name='layer')),
                ('name_fr', models.CharField(blank=True, max_length=200, verbose_name='nom (fr)')),
                ('name_nl', models.CharField(blank=True, max_length=200, verbose_name='nom (nl)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='nom (en)')),
                ('reciprocit', models.CharField(blank=True, max_length=100, verbose_name='reciprocit')),
                ('area', models.FloatField(blank=True, null=True, verbose_name='aire (m²)')),
                ('perimeter', models.FloatField(blank=True, null=True, verbose_name='périmètre (m)')),
                ('attributes_json', models.JSONField(default=dict, verbose_name='attributs source')),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gis_polygons', to='core.commune')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polygons', to='gis_data.gissourceversion')),
            ],
            options={
                'verbose_name': 'polygone GIS',
                'verbose_name_plural': 'polygones GIS',
                'ordering': ['niscode', 'zonecode'],
            },
        ),
        migrations.AddConstraint(
            model_name='gissourceversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='only_one_active_gis_version'),
        ),
        migrations.AddIndex(
            model_name='gispolygon',
            index=models.Index(fields=['version', 'zonecode'], name='gis_data_gi_version_286722_idx'),
        ),
        migrations.AddIndex(
            model_name='gispolygon',
            index=models.Index(fields=['version', 'niscode'], name='gis_data_gi_version_9f26ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='gispolygon',
            constraint=models.UniqueConstraint(fields=('version', 'zonecode'), name='unique_zonecode_per_version'),
        ),
    ]
