# Generated by Django 5.1.4 on 2026-04-25 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gispolygon',
            name='unique_zonecode_per_version',
        ),
    ]
