# Generated by Django 5.1.4 on 2026-04-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niscode', models.CharField(max_length=10, unique=True, verbose_name='code NIS')),
                ('name_fr', models.CharField(max_length=100, verbose_name='nom (fr)')),
                ('name_nl', models.CharField(max_length=100, verbose_name='nom (nl)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='nom (en)')),
            ],
            options={
                'verbose_name': 'commune',
                'verbose_name_plural': 'communes',
                'ordering': ['name_fr'],
            },
        ),
    ]
