# Generated by Django 5.1.4 on 2026-04-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_communes'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='postal_codes',
            field=models.CharField(blank=True, default='', help_text='CSV ex: 1000,1020,1120 — utilisé pour auto-remplir la commune', max_length=200, verbose_name='codes postaux'),
        ),
    ]
