# Generated by Django 5.1.4 on 2026-04-25 19:40

import apps.payments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permits', '0005_seed_default_commune_policies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.IntegerField(verbose_name='montant (centimes)')),
                ('method', models.CharField(choices=[('internal_free', 'Paiement interne gratuit'), ('simulation', 'Simulation (test)')], default='internal_free', max_length=30, verbose_name='méthode')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'Traitement'), ('succeeded', 'Validé'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='statut')),
                ('reference', models.CharField(db_index=True, default=apps.payments.models._generate_reference, max_length=64, unique=True, verbose_name='référence')),
                ('external_transaction_id', models.CharField(blank=True, default='', max_length=120, verbose_name='ID transaction externe')),
                ('failure_reason', models.TextField(blank=True, verbose_name="raison d'échec")),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_from_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('confirmed_from_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='permits.permit')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'ordering': ['-initiated_at'],
                'indexes': [models.Index(fields=['permit', 'status'], name='payments_pa_permit__b5f64c_idx'), models.Index(fields=['citizen', 'status'], name='payments_pa_citizen_18ffce_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'succeeded')), fields=('permit',), name='one_succeeded_payment_per_permit')],
            },
        ),
    ]
