# Generated by Django 5.1.4 on 2026-04-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Stripe PaymentIntent'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_session_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Stripe session id'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('internal_free', 'Paiement interne gratuit'), ('stripe', 'Carte bancaire (Stripe)'), ('simulation', 'Simulation (test)')], default='internal_free', max_length=30, verbose_name='méthode'),
        ),
    ]
