# Generated by Django 5.1.4 on 2026-04-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_stripe_payment_intent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_brand',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='marque carte'),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_holder',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='titulaire'),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_last4',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='4 derniers chiffres'),
        ),
        migrations.AddField(
            model_name='payment',
            name='paypal_capture_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='PayPal capture id'),
        ),
        migrations.AddField(
            model_name='payment',
            name='paypal_order_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='PayPal order id'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('card', 'Carte bancaire'), ('paypal', 'PayPal'), ('stripe', 'Carte bancaire (Stripe)'), ('internal_free', 'Paiement interne gratuit'), ('simulation', 'Simulation (test)')], default='internal_free', max_length=30, verbose_name='méthode'),
        ),
    ]
