# Generated by Django 5.1.4 on 2026-04-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_card_brand_payment_card_holder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paypal_capture_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paypal_order_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('card', 'Carte bancaire'), ('stripe', 'Carte bancaire (Stripe)'), ('internal_free', 'Paiement interne gratuit'), ('simulation', 'Simulation (test)')], default='internal_free', max_length=30, verbose_name='méthode'),
        ),
    ]
