# Generated by Django 5.1.4 on 2026-04-25 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='plaque')),
                ('vehicle_type', models.CharField(choices=[('passenger_car', 'Voiture particulière'), ('lcv', 'Véhicule utilitaire léger'), ('motorcycle', 'Moto'), ('electric_scooter', 'Trottinette électrique'), ('other', 'Autre')], default='passenger_car', max_length=30, verbose_name='type')),
                ('brand', models.CharField(max_length=50, verbose_name='marque')),
                ('model', models.CharField(max_length=50, verbose_name='modèle')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='couleur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'véhicule',
                'verbose_name_plural': 'véhicules',
                'ordering': ['plate'],
            },
        ),
    ]
