# Generated by Django 5.1.4 on 2026-04-25 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='registration_document',
            field=models.FileField(blank=True, help_text='PDF, JPG, PNG ou WebP — max 5 Mo.', null=True, upload_to='vehicles/registration_documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp'])], verbose_name="certificat d'immatriculation"),
        ),
    ]
