# Generated by Django 5.1.4 on 2026-04-25 15:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_registration_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlateChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_plate', models.CharField(max_length=20, verbose_name='nouvelle plaque')),
                ('new_registration_document', models.FileField(blank=True, help_text='PDF, JPG, PNG ou WebP — max 5 Mo.', null=True, upload_to='vehicles/plate_change_documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp'])], verbose_name="nouveau certificat d'immatriculation")),
                ('reason', models.TextField(blank=True, verbose_name='motif')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Refusée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='statut')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True, verbose_name='notes')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plate_change_requests', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'demande de changement de plaque',
                'verbose_name_plural': 'demandes de changement de plaque',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
