# Generated by Django 5.1.4 on 2026-04-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_platechangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='archive_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name="motif d'archivage"),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='archivé le'),
        ),
    ]
