# Generated by Django 5.1.4 on 2026-04-25 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gis_data', '0002_remove_gispolygon_unique_zonecode_per_version'),
        ('rules', '0001_initial'),
        ('vehicles', '0003_platechangerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_type', models.CharField(choices=[('resident', 'Riverain'), ('visitor', 'Visiteur'), ('professional', 'Professionnel')], max_length=20, verbose_name='type')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumise'), ('manual_review', 'Revue manuelle'), ('refused', 'Refusée'), ('awaiting_payment', 'En attente de paiement'), ('active', 'Active'), ('suspended', 'Suspendue'), ('expired', 'Expirée'), ('cancelled', 'Annulée')], default='draft', max_length=20, verbose_name='statut')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('attribution_snapshot', models.JSONField(blank=True, default=dict, verbose_name="snapshot d'attribution")),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True, verbose_name='notes de décision')),
                ('awaiting_payment_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('price_cents', models.IntegerField(default=0, verbose_name='prix (centimes)')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('suspension_reason', models.TextField(blank=True, verbose_name='raison de suspension')),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permits', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_polygon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gis_data.gispolygon')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permits', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'carte',
                'verbose_name_plural': 'cartes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PermitZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_code', models.CharField(max_length=100, verbose_name='zonecode')),
                ('is_main', models.BooleanField(default=False, verbose_name='zone principale')),
                ('source', models.CharField(choices=[('polygon', 'Polygone GIS'), ('rule', 'Règle métier'), ('manual', 'Saisie manuelle')], max_length=20, verbose_name='provenance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='permits.permit')),
                ('source_polygon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gis_data.gispolygon')),
                ('source_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rules.polygonrule')),
            ],
            options={
                'verbose_name': 'zone de carte',
                'verbose_name_plural': 'zones de cartes',
            },
        ),
        migrations.AddIndex(
            model_name='permit',
            index=models.Index(fields=['citizen', 'status'], name='permits_per_citizen_985c5d_idx'),
        ),
        migrations.AddIndex(
            model_name='permit',
            index=models.Index(fields=['vehicle', 'status'], name='permits_per_vehicle_872996_idx'),
        ),
        migrations.AddConstraint(
            model_name='permitzone',
            constraint=models.UniqueConstraint(fields=('permit', 'zone_code'), name='unique_zone_per_permit'),
        ),
        migrations.AddConstraint(
            model_name='permitzone',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('permit',), name='one_main_zone_per_permit'),
        ),
    ]
