# Generated by Django 5.1.4 on 2026-04-25 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('permits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permits', to='companies.company'),
        ),
        migrations.CreateModel(
            name='VisitorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='code')),
                ('plate', models.CharField(max_length=20, verbose_name='plaque visiteur')),
                ('valid_from', models.DateTimeField(verbose_name='valide à partir de')),
                ('valid_until', models.DateTimeField(verbose_name="valide jusqu'au")),
                ('status', models.CharField(choices=[('active', 'Actif'), ('cancelled', 'Annulé')], default='active', max_length=20, verbose_name='statut')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_codes', to='permits.permit')),
            ],
            options={
                'verbose_name': 'code visiteur',
                'verbose_name_plural': 'codes visiteurs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['permit', 'status'], name='permits_vis_permit__20c81f_idx'), models.Index(fields=['plate', 'valid_from', 'valid_until'], name='permits_vis_plate_451144_idx')],
            },
        ),
    ]
