# Generated by Django 5.1.4 on 2026-04-25 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_communes'),
        ('permits', '0002_permit_company_visitorcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='target_commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commune'),
        ),
        migrations.CreateModel(
            name='PermitConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_price_cents', models.IntegerField(default=1000, verbose_name='prix riverain (centimes)')),
                ('visitor_price_cents', models.IntegerField(default=0, verbose_name='prix visiteur (centimes)')),
                ('professional_price_cents', models.IntegerField(default=5000, verbose_name='prix professionnel (centimes)')),
                ('visitor_codes_per_year', models.IntegerField(default=100, verbose_name='codes visiteurs / an')),
                ('visitor_code_default_hours', models.IntegerField(default=4, verbose_name='durée code visiteur — défaut (h)')),
                ('visitor_code_max_hours', models.IntegerField(default=72, verbose_name='durée code visiteur — max (h)')),
                ('permit_default_validity_days', models.IntegerField(default=365, verbose_name='validité par défaut (jours)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'configuration des cartes',
                'verbose_name_plural': 'configurations des cartes',
            },
        ),
    ]
