# Generated by Django 5.1.4 on 2026-04-25 17:59

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_communes'),
        ('permits', '0003_permit_target_commune_permitconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permitconfig',
            options={'verbose_name': 'configuration globale', 'verbose_name_plural': 'configurations globales'},
        ),
        migrations.AddField(
            model_name='permitconfig',
            name='allow_cumul_resident_pro',
            field=models.BooleanField(default=True, verbose_name='autoriser cumul riverain + pro'),
        ),
        migrations.AddField(
            model_name='permitconfig',
            name='max_active_pro_per_citizen',
            field=models.IntegerField(default=3, verbose_name='nb max cartes pro actives / citoyen'),
        ),
        migrations.AddField(
            model_name='permitconfig',
            name='max_companies_per_citizen',
            field=models.IntegerField(default=5, verbose_name='nb max entreprises / citoyen'),
        ),
        migrations.AddField(
            model_name='permitconfig',
            name='max_vehicles_per_citizen',
            field=models.IntegerField(default=5, verbose_name='nb max véhicules / citoyen'),
        ),
        migrations.AlterField(
            model_name='permitconfig',
            name='professional_price_cents',
            field=models.IntegerField(default=5000, verbose_name='prix professionnel défaut (centimes)'),
        ),
        migrations.AlterField(
            model_name='permitconfig',
            name='resident_price_cents',
            field=models.IntegerField(default=1000, verbose_name='prix riverain défaut (centimes)'),
        ),
        migrations.AlterField(
            model_name='permitconfig',
            name='visitor_price_cents',
            field=models.IntegerField(default=0, verbose_name='prix visiteur défaut (centimes)'),
        ),
        migrations.CreateModel(
            name='CommunePermitPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_type', models.CharField(choices=[('resident', 'Riverain'), ('visitor', 'Visiteur'), ('professional', 'Professionnel')], max_length=20, verbose_name='type de carte')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='type proposé dans cette commune')),
                ('auto_attribution', models.BooleanField(default=True, help_text="Si décoché, toute demande passe en revue manuelle même si l'engine ne le requiert pas.", verbose_name='attribution automatique')),
                ('validity_days', models.IntegerField(default=365, verbose_name='validité (jours)')),
                ('price_strategy', models.CharField(choices=[('fixed', 'Prix fixe'), ('grid', 'Grille (selon rang)'), ('exponential', 'Exponentielle (base × facteur^(rang-1))')], default='fixed', max_length=20, verbose_name='stratégie de prix')),
                ('price_fixed_cents', models.IntegerField(default=0, help_text='Utilisé si stratégie = fixed.', verbose_name='prix fixe (centimes)')),
                ('price_grid', models.JSONField(blank=True, default=list, help_text='Liste de [rang_seuil, prix_centimes] — ex: [[1,1000],[2,2500],[3,5000]].', verbose_name='grille tarifaire')),
                ('price_exponential_base_cents', models.IntegerField(default=1000, verbose_name='base exponentielle (centimes)')),
                ('price_exponential_factor', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=6, verbose_name='facteur exponentiel')),
                ('max_active_per_citizen', models.IntegerField(blank=True, null=True, verbose_name='nb max cartes actives / citoyen (vide = illimité)')),
                ('max_vehicles_per_card', models.IntegerField(blank=True, help_text='Pertinent surtout pour la carte professionnelle.', null=True, verbose_name='nb max véhicules / carte (vide = illimité)')),
                ('effective_from', models.DateField(default=datetime.date.today, verbose_name='effective à partir du')),
                ('effective_until', models.DateField(blank=True, null=True, verbose_name="effective jusqu'au")),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_policies', to='core.commune')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'politique commune × type',
                'verbose_name_plural': 'politiques commune × type',
                'ordering': ['commune__name_fr', 'permit_type', '-effective_from'],
                'indexes': [models.Index(fields=['commune', 'permit_type', 'effective_from'], name='permits_com_commune_d623bd_idx')],
            },
        ),
    ]
