# Generated by Django 5.1.4 on 2026-05-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0005_seed_default_commune_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='expiry_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
