# Generated by Django 5.1.4 on 2026-04-26 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(blank=True, help_text="Snapshot — préservé même si l'utilisateur change de rôle ensuite.", max_length=20, verbose_name="rôle au moment de l'action")),
                ('action', models.CharField(choices=[('permit_submitted', 'Carte soumise'), ('permit_approved', 'Carte approuvée (revue manuelle)'), ('permit_refused', 'Carte refusée'), ('permit_activated', 'Carte activée'), ('permit_suspended', 'Carte suspendue'), ('permit_expired', 'Carte expirée'), ('permit_cancelled', 'Carte annulée'), ('payment_succeeded', 'Paiement validé'), ('payment_refunded', 'Paiement remboursé'), ('payment_cancelled', 'Paiement annulé'), ('payment_simulated', 'Paiement simulé (debug/staff)'), ('user_role_changed', 'Rôle utilisateur modifié'), ('user_basics_updated', 'Profil utilisateur modifié'), ('user_deactivated', 'Utilisateur désactivé'), ('user_reactivated', 'Utilisateur réactivé'), ('password_reset_sent', 'Email de reset envoyé'), ('auth_failed', "Échec d'authentification"), ('api_token_issued', 'Token API émis'), ('api_token_revoked', 'Token API révoqué'), ('api_check_right', 'Appel API check-right'), ('vehicle_archived', 'Véhicule archivé'), ('vehicle_restored', 'Véhicule restauré'), ('policy_changed', 'Politique commune modifiée'), ('permit_config_changed', 'Configuration globale modifiée'), ('polygon_rule_changed', 'Règle de polygone modifiée'), ('gis_imported', 'Import GIS effectué'), ('gis_active_version_changed', 'Version GIS active changée')], db_index=True, max_length=50, verbose_name='action')),
                ('severity', models.CharField(choices=[('info', 'Information'), ('notice', 'Notable'), ('warning', 'Avertissement'), ('critical', 'Critique')], db_index=True, default='info', max_length=10, verbose_name='sévérité')),
                ('target_type', models.CharField(blank=True, db_index=True, help_text='Ex: permit, payment, user, vehicle, gis_polygon, api_token.', max_length=50, verbose_name='type de cible')),
                ('target_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='id de la cible')),
                ('target_label', models.CharField(blank=True, help_text="Snapshot textuel (str(target)) — survit à la suppression de l'objet.", max_length=200, verbose_name='libellé de la cible')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='contenu')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP source')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Null = action déclenchée par le système (cron, signal).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "entrée d'audit",
                'verbose_name_plural': "journal d'audit",
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='audit_audit_action_0c6a84_idx'), models.Index(fields=['actor', '-created_at'], name='audit_audit_actor_i_1175ab_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_audit_target__2d648a_idx')],
            },
        ),
    ]
