# Generated by Django 5.1.4 on 2026-05-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('permit_submitted', 'Carte soumise'), ('permit_approved', 'Carte approuvée (revue manuelle)'), ('permit_refused', 'Carte refusée'), ('permit_activated', 'Carte activée'), ('permit_suspended', 'Carte suspendue'), ('permit_expired', 'Carte expirée'), ('permit_cancelled', 'Carte annulée'), ('payment_succeeded', 'Paiement validé'), ('payment_refunded', 'Paiement remboursé'), ('payment_cancelled', 'Paiement annulé'), ('payment_simulated', 'Paiement simulé (debug/staff)'), ('user_role_changed', 'Rôle utilisateur modifié'), ('user_basics_updated', 'Profil utilisateur modifié'), ('user_deactivated', 'Utilisateur désactivé'), ('user_reactivated', 'Utilisateur réactivé'), ('password_reset_sent', 'Email de reset envoyé'), ('auth_failed', "Échec d'authentification"), ('api_token_issued', 'Token API émis'), ('api_token_revoked', 'Token API révoqué'), ('api_check_right', 'Appel API check-right'), ('vehicle_archived', 'Véhicule archivé'), ('vehicle_restored', 'Véhicule restauré'), ('policy_changed', 'Politique commune modifiée'), ('permit_config_changed', 'Configuration globale modifiée'), ('polygon_rule_changed', 'Règle de polygone modifiée'), ('gis_imported', 'Import GIS effectué'), ('gis_active_version_changed', 'Version GIS active changée'), ('csv_exported', 'Export CSV téléchargé'), ('rgpd_purged', 'Purge RGPD')], db_index=True, max_length=50, verbose_name='action'),
        ),
    ]
