# Generated by Django 5.1.4 on 2026-04-25 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_seed_communes'),
        ('gis_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolygonRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_type', models.CharField(choices=[('resident', 'Riverain'), ('visitor', 'Visiteur'), ('professional', 'Professionnel')], max_length=20, verbose_name='type de carte')),
                ('action_type', models.CharField(choices=[('add_zone', 'Ajouter une zone'), ('replace_main_zone', 'Remplacer la zone principale'), ('manual_review', 'Forcer revue manuelle'), ('deny', "Refuser l'attribution automatique")], max_length=30, verbose_name='action')),
                ('target_zone_code', models.CharField(blank=True, help_text='Requis pour ADD_ZONE et REPLACE_MAIN_ZONE.', max_length=100, verbose_name='zonecode cible')),
                ('priority', models.IntegerField(default=100, help_text='Plus petit = plus prioritaire (appliqué en premier).', verbose_name='priorité')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='valide à partir du')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name="valide jusqu'au")),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polygon_rules', to='core.commune')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('polygon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='gis_data.gispolygon')),
            ],
            options={
                'verbose_name': 'règle polygone',
                'verbose_name_plural': 'règles polygones',
                'ordering': ['priority', 'id'],
            },
        ),
    ]
